name:  Task 1

on:
  push:
jobs:
  task-job:
    runs-on: ubuntu-latest

    steps:
      - name: hostname
        run: hostname
      - name: Print current user
        run: whoami
      - name: install package
        run: |
          sudo apt update
          sudo apt install -y tree
